#!/bin/bash

profile=~/.mozilla/firefox/

echo "Before..."
find "$profile" -name '*.sqlite' -print0 | xargs -0 du -hc | grep total

find "$profile" -name '*.sqlite' -exec sqlite3 '{}' VACUUM ';'
find "$profile" -name '*.sqlite' -exec sqlite3 '{}' REINDEX ';'

echo "After:"
find "$profile" -name '*.sqlite' -print0 | xargs -0 du -hc | grep total
